In [1]:
import numpy as np


In [7]:
l = [1,2,3,4,4]


In [8]:
type(l)

list

In [10]:
a = np.array(l)

In [11]:
type(a)

numpy.ndarray

In [12]:
a

array([1, 2, 3, 4, 4])

In [13]:
a1 = np.array([[1,2,3],[3,4,5]])

In [14]:
a1

array([[1, 2, 3],
       [3, 4, 5]])

In [15]:
a2 = np.array([[[1,2,3],[4,.5,6]]])

In [16]:
a2

array([[[1. , 2. , 3. ],
        [4. , 0.5, 6. ]]])

In [17]:
a     #[]represented this is an one dimentional

array([1, 2, 3, 4, 4])

In [18]:
a1     #[[]] represent two diamentional

array([[1, 2, 3],
       [3, 4, 5]])

In [19]:
a2    # represent three dimention

array([[[1. , 2. , 3. ],
        [4. , 0.5, 6. ]]])

In [20]:
a.ndim

1

In [21]:
a1.ndim

2

In [22]:
a2.ndim


3

In [38]:
a3 = np.array([[[1,2,3],[3,4,5]],[[1,2,3],[3,4,5]],[[1,2,3],[3,4,5]]])

In [39]:
a3

array([[[1, 2, 3],
        [3, 4, 5]],

       [[1, 2, 3],
        [3, 4, 5]],

       [[1, 2, 3],
        [3, 4, 5]]])

In [40]:
a3.ndim

3

In [41]:
 l = [1,2,3,4]

In [42]:
np.asarray(l)

array([1, 2, 3, 4])

In [43]:
np.matrix(l)

matrix([[1, 2, 3, 4]])

In [48]:
np.fromfunction(lambda i,j : i==j ,(3,4))   #it ony work for 2 dimentional array

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [49]:
np.random.rand(2,3)

array([[0.86034221, 0.31274602, 0.70468582],
       [0.20096703, 0.31325001, 0.52819064]])

In [54]:
np.random.rand(2,3,2)

array([[[0.13265171, 0.21851631],
        [0.60168613, 0.21127718],
        [0.64239391, 0.58392689]],

       [[0.38522247, 0.07244752],
        [0.24657918, 0.56000938],
        [0.0444886 , 0.94106074]]])

In [56]:
np.random.rand(2,3,2,2)

array([[[[0.92989593, 0.5414398 ],
         [0.53059813, 0.93641262]],

        [[0.33067163, 0.31251673],
         [0.29127649, 0.63140938]],

        [[0.17964095, 0.20944859],
         [0.07253604, 0.94337963]]],


       [[[0.93432172, 0.23498114],
         [0.97684058, 0.11221146]],

        [[0.14235777, 0.23868674],
         [0.55944998, 0.39969095]],

        [[0.99029197, 0.12776405],
         [0.75593106, 0.52813454]]]])

In [59]:
np.random.rand(3,4,4)

array([[[0.87224064, 0.55027042, 0.43305386, 0.52942897],
        [0.6196611 , 0.44752174, 0.90078902, 0.05520839],
        [0.3428827 , 0.00659767, 0.74076304, 0.45492565],
        [0.76180345, 0.18196154, 0.19866813, 0.54284051]],

       [[0.51559525, 0.23156877, 0.85483795, 0.82623042],
        [0.30723297, 0.58203975, 0.51822168, 0.75599232],
        [0.66809958, 0.81619573, 0.85456264, 0.35350302],
        [0.67575851, 0.83954206, 0.85899331, 0.86855011]],

       [[0.56292568, 0.0675911 , 0.30475998, 0.84348716],
        [0.24159495, 0.97321882, 0.01015144, 0.37678608],
        [0.59911148, 0.93191374, 0.83191635, 0.60347748],
        [0.20443501, 0.20634017, 0.90985783, 0.55110671]]])

In [67]:

d = np.random.rand(3,4)

In [69]:
import pandas as pd
pd.DataFrame(d)

0         1         2         3
0  0.487667  0.619806  0.105206  0.136606
1  0.486740  0.541241  0.723790  0.052564
2  0.114834  0.523158  0.121817  0.316147

In [61]:
np.random.randn(3,4,5)

array([[[-0.61991604,  1.24677341, -0.51991486,  2.64990502,
          2.19937867],
        [-1.69252289, -0.17230565, -0.72364366,  0.27384438,
          0.19799206],
        [ 0.34206637, -1.07192718,  0.16852274, -0.72580809,
         -0.01678891],
        [-0.04565797,  0.08278793, -0.21948743, -1.51558259,
         -0.55546189]],

       [[ 0.78435996,  1.06902579, -0.74585424,  0.64529434,
          0.56184867],
        [ 0.73236507, -0.73640456, -0.53260973,  0.01673041,
          0.03274424],
        [-0.26535545, -0.49509521,  0.18965389,  0.05299677,
          0.59190951],
        [-1.99308974, -0.25628655,  0.68649047, -0.92598252,
          0.47346141]],

       [[ 0.57025425, -0.62487286, -0.35311195, -1.24883021,
         -0.3015806 ],
        [ 1.11867976, -1.05924311,  0.62848102,  1.48681207,
         -0.49065102],
        [-0.91330754, -1.29803432, -1.45132121,  1.71026871,
         -2.33419268],
        [ 0.36308827,  2.05811791,  0.30940478,  2.56406527,
         -1

In [62]:
np.random.randn(3,4,4)

array([[[ 0.85436889, -2.28468571,  0.77079937,  0.55417264],
        [ 1.03674819, -0.63609534, -0.35966616, -0.62298121],
        [ 0.46105374, -0.48964916,  0.13168495, -0.62930167],
        [-0.70570492,  0.8308103 ,  0.74963388, -0.71071969]],

       [[ 0.91826892, -0.48934445,  0.82216933, -0.52115477],
        [ 0.73588887,  0.659093  , -0.16136222,  1.04607611],
        [ 1.21807285,  0.34666803,  1.01752566,  2.06136559],
        [-0.48828348, -0.03214267, -0.06336691, -0.12794635]],

       [[-0.58887661, -0.47957923,  0.46822616,  0.74544769],
        [-2.21518149, -0.46953646,  1.28638836,  0.8122775 ],
        [-0.7710009 , -0.77071337, -0.54593211,  0.02567483],
        [-1.02639856, -0.23162767, -0.30338496, -1.01434435]]])

In [63]:
np.random.randint(3,4,4)

array([3, 3, 3, 3])

In [70]:
d1 = np.random.randint(0,10,(4,4,2))   #4*4*2=32

In [71]:
d1

array([[[0, 4],
        [8, 7],
        [4, 0],
        [6, 8]],

       [[3, 4],
        [2, 8],
        [6, 7],
        [9, 4]],

       [[9, 6],
        [2, 7],
        [3, 1],
        [6, 6]],

       [[4, 5],
        [8, 8],
        [7, 8],
        [9, 4]]])

In [75]:
d1.reshape(16,2)

array([[0, 4],
       [8, 7],
       [4, 0],
       [6, 8],
       [3, 4],
       [2, 8],
       [6, 7],
       [9, 4],
       [9, 6],
       [2, 7],
       [3, 1],
       [6, 6],
       [4, 5],
       [8, 8],
       [7, 8],
       [9, 4]])

In [76]:
d1.reshape(8,4)

array([[0, 4, 8, 7],
       [4, 0, 6, 8],
       [3, 4, 2, 8],
       [6, 7, 9, 4],
       [9, 6, 2, 7],
       [3, 1, 6, 6],
       [4, 5, 8, 8],
       [7, 8, 9, 4]])

In [65]:
np.random.randint(0,10,(4,2,2))

array([[[7, 5],
        [8, 7]],

       [[9, 9],
        [8, 7]],

       [[8, 6],
        [2, 9]],

       [[0, 0],
        [4, 7]]])

In [ ]:
d1