In [1]:
import numpy as np


In [2]:
range(10)

range(0, 10)

In [3]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
list(range(3,10))

[3, 4, 5, 6, 7, 8, 9]

In [9]:
 list(range(3,1 0.5))

TypeError: 'float' object cannot be interpreted as an integer

In [12]:
np.arange(10) #it is an advanced version of an range function

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(.5,10)

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [14]:
np.arange(5,-4,-1)

array([ 5,  4,  3,  2,  1,  0, -1, -2, -3])

In [16]:
np.arange(5,-4,-.5)

array([ 5. ,  4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5,  1. ,  0.5,  0. ,
       -0.5, -1. , -1.5, -2. , -2.5, -3. , -3.5])

In [17]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [18]:
list(np.linspace(1,5,20))

[1.0,
 1.2105263157894737,
 1.4210526315789473,
 1.631578947368421,
 1.8421052631578947,
 2.052631578947368,
 2.263157894736842,
 2.473684210526316,
 2.6842105263157894,
 2.894736842105263,
 3.1052631578947367,
 3.3157894736842106,
 3.526315789473684,
 3.7368421052631575,
 3.9473684210526314,
 4.157894736842105,
 4.368421052631579,
 4.578947368421052,
 4.789473684210526,
 5.0]

In [19]:
list(np.linspace(1,5,20,retstep=True))

[array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
        2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
        3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
        4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ]),
 0.21052631578947367]

In [20]:
np.logspace(1,50,10)  #similar to linespace

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

In [21]:
 np.logspace(1,50,20)

array([1.00000000e+01, 3.79269019e+03, 1.43844989e+06, 5.45559478e+08,
       2.06913808e+11, 7.84759970e+13, 2.97635144e+16, 1.12883789e+19,
       4.28133240e+21, 1.62377674e+24, 6.15848211e+26, 2.33572147e+29,
       8.85866790e+31, 3.35981829e+34, 1.27427499e+37, 4.83293024e+39,
       1.83298071e+42, 6.95192796e+44, 2.63665090e+47, 1.00000000e+50])

In [23]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [24]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.zeros((3,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [27]:
 np.empty((2,3))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [1.29061074e-306, 1.89146896e-307, 7.56571288e-307]])

In [30]:
a = np.eye(4)

In [31]:
 a.shape

(4, 4)

In [32]:
a.size

16

In [36]:
a.ndim

2